/**
 * @description Global style supported list
 * @see {@link https://tailwindcss.com/docs/theme#configuration-reference configuration reference}
 */
export type TailwindGlobalPluginKey = "color" | "opacity" | "sizing"

/**
 * @description Nest conditions
 * @description should be only **one** string literal
 * @example
 * type MyTailwindest = Tailwindest<{
 *      screens: {
 *          conditionA: "@my-condition",
 *          // ✅ only one string union
 *          conditionB: "@don't-do-this" | "@don't-do-this-plz"
 *          // ❌ more than one string union
 *      }
 * }>
 */
export type TailwindNestPluginKey =
    | "conditionA"
    | "conditionB"
    | "conditionC"
    | "conditionD"
    | "conditionE"
    | "conditionF"
    | "conditionG"
    | "conditionH"
    | "conditionI"
    | "conditionJ"
    | "conditionK"
    | "conditionL"
    | "conditionM"
    | "conditionN"
    | "conditionO"
    | "conditionP"
    | "conditionQ"
    | "conditionR"
    | "conditionS"
    | "conditionT"
    | "conditionU"
    | "conditionV"
    | "conditionW"
    | "conditionX"
    | "conditionY"
    | "conditionZ"

/**
 * @description Style supported list
 * @see {@link https://tailwindcss.com/docs/theme#configuration-reference configuration reference}
 */
export type TailwindStylePluginKey =
    | "columns"
    | "animation"
    | "aspectRatio"
    | "backdropBlur"
    | "backdropBrightness"
    | "backdropContrast"
    | "backdropGrayscale"
    | "backdropHueRotate"
    | "backdropInvert"
    | "backdropOpacity"
    | "backdropSaturate"
    | "backdropSepia"
    | "backgroundColor"
    | "backgroundImage"
    | "backgroundPosition"
    | "backgroundSize"
    | "blur"
    | "brightness"
    | "borderColor"
    | "borderRadius"
    | "borderSpacing"
    | "borderWidth"
    | "boxShadow"
    | "boxShadowColor"
    | "caretColor"
    | "accentColor"
    | "contrast"
    | "content"
    | "cursor"
    | "divideColor"
    | "divideWidth"
    | "dropShadow"
    | "fill"
    | "grayscale"
    | "hueRotate"
    | "invert"
    | "flex"
    | "flexBasis"
    | "flexGrow"
    | "flexShrink"
    | "fontFamily"
    | "fontSize"
    | "fontWeight"
    | "gap"
    | "gradientColorStops"
    | "gridAutoColumns"
    | "gridAutoRows"
    | "gridColumn"
    | "gridColumnEnd"
    | "gridColumnStart"
    | "gridRow"
    | "gridRowStart"
    | "gridRowEnd"
    | "gridTemplateColumns"
    | "gridTemplateRows"
    | "height"
    | "inset"
    | "letterSpacing"
    | "lineHeight"
    | "listStyleType"
    | "margin"
    | "maxHeight"
    | "maxWidth"
    | "minHeight"
    | "minWidth"
    | "objectPosition"
    | "opacity"
    | "order"
    | "padding"
    | "outlineColor"
    | "outlineOffset"
    | "outlineWidth"
    | "ringColor"
    | "ringOffsetColor"
    | "ringOffsetWidth"
    | "ringWidth"
    | "rotate"
    | "saturate"
    | "scale"
    | "scrollMargin"
    | "scrollPadding"
    | "sepia"
    | "skew"
    | "space"
    | "stroke"
    | "strokeWidth"
    | "textColor"
    | "textDecorationColor"
    | "textDecorationThickness"
    | "textUnderlineOffset"
    | "textIndent"
    | "transformOrigin"
    | "transitionDelay"
    | "transitionDuration"
    | "transitionProperty"
    | "transitionTimingFunction"
    | "translate"
    | "width"
    | "willChange"
    | "zIndex"
