import type {
    FirstDepthNestCondition,
    NestIdentifierSymbols,
    PrefixedArbitraryNestGroups,
    PrefixedNestGroups,
    RemoveIdentifier,
    TailwindestConfig,
    TailwindIdentifier,
    UseArbitraryValue,
    With,
} from "./types/core"
export type { TailwindestConfig, TailwindestInterface } from "./types/core"

type CombineNestConditionAtCurrentNestStyleProperty<
    NestStyle,
    Identifier extends string = TailwindIdentifier,
    UseArbitrary extends true | false = true,
    NestCondition extends string = FirstDepthNestCondition,
> = {
    [NestKey in keyof NestStyle]?: NestStyle[NestKey] extends string
        ? NestCondition extends FirstDepthNestCondition
            ? With<NestStyle[NestKey], UseArbitrary>
            : With<
                  `${RemoveIdentifier<NestCondition, Identifier>}:${NestStyle[NestKey]}`,
                  UseArbitrary
              >
        : never
}

type CombineArbitraryNestStyleProperty<NestStyle> = {
    [NestKey in keyof NestStyle]?: NestStyle[NestKey] extends string
        ? With<NestStyle[NestKey], true>
        : never
}

// Arbitrary nest keys cannot safely form exact `${key}:${value}` unions for
// large generated Tailwind types without triggering TS2590.
type GetArbitraryNestStyle<
    TailwindNestGroups extends string,
    Tailwind,
    ArbitraryNestGroups extends string = never,
> = {
    [CurrentNestCondition in TailwindNestGroups]?: GetArbitraryNestStyle<
        Exclude<TailwindNestGroups, CurrentNestCondition>,
        Tailwind,
        ArbitraryNestGroups
    >
} & ([ArbitraryNestGroups] extends [never]
    ? {}
    : {
          [CurrentNestCondition in ArbitraryNestGroups]?: GetArbitraryNestStyle<
              TailwindNestGroups,
              Tailwind,
              ArbitraryNestGroups
          >
      }) &
    CombineArbitraryNestStyleProperty<Tailwind>

type CombineArbitraryNestConditionAtCurrentNestStyleProperty<
    TailwindNestGroups extends string,
    Tailwind,
    ArbitraryNestGroups extends string = never,
> = [ArbitraryNestGroups] extends [never]
    ? {}
    : {
          [CurrentNestCondition in ArbitraryNestGroups]?: GetArbitraryNestStyle<
              TailwindNestGroups,
              Tailwind,
              ArbitraryNestGroups
          >
      }

export type GetNestStyle<
    TailwindNestGroups extends string,
    Tailwind,
    Identifier extends string = TailwindIdentifier,
    UseArbitrary extends true | false = true,
    ArbitraryNestGroups extends string = never,
    $$Nest$$ extends string = FirstDepthNestCondition,
> = {
    [CurrentNestCondition in Exclude<
        TailwindNestGroups,
        $$Nest$$
    >]?: GetNestStyle<
        Exclude<TailwindNestGroups, CurrentNestCondition | $$Nest$$>,
        Tailwind,
        Identifier,
        UseArbitrary,
        ArbitraryNestGroups,
        `${$$Nest$$}:${RemoveIdentifier<CurrentNestCondition, Identifier>}`
    >
} & CombineArbitraryNestConditionAtCurrentNestStyleProperty<
    Exclude<TailwindNestGroups, $$Nest$$>,
    Tailwind,
    ArbitraryNestGroups
> &
    CombineNestConditionAtCurrentNestStyleProperty<
        Tailwind,
        Identifier,
        UseArbitrary,
        $$Nest$$
    >

/**
 * Create tailwindest typeset
 *
 * @description Run `npx create-tailwind-type` to generate tailwind type defs.
 * ```bash
 * npx create-tailwind-type
 * ```
 * @see {@link https://github.com/danpacho/tailwindest#create-tailwind-type create-tailwind-type}
 *
 * @example
 * ```ts
 * // 1. import generated types
 * import type { Tailwind, TailwindNestGroups } from "~/tailwind.ts"
 *
 * // 2. create type
 * export type Tailwindest = CreateTailwindest<{
 *      tailwind: Tailwind
 *      tailwindNestGroups: TailwindNestGroups
 *      useArbitrary: true
 *      useArbitraryNestGroups: true
 *      groupPrefix: "#" // optional
 * }>
 * ```
 */
type _BaseNestStyle<Config extends TailwindestConfig> = GetNestStyle<
    PrefixedNestGroups<Config>,
    Config["tailwind"],
    NestIdentifierSymbols<Config>,
    UseArbitraryValue<Config>,
    PrefixedArbitraryNestGroups<Config>
>

export type CreateTailwindest<Config extends TailwindestConfig> =
    _BaseNestStyle<Config>

/**
 * Create tailwind literal typeset
 *
 * @description Prefer importing the precomputed `TailwindLiteral` from the
 * `tailwind_literal.ts` file generated by `create-tailwind-type`. This helper
 * remains available as a compatibility fallback, but it may be expensive for
 * large generated `Tailwind` types because it evaluates `Tailwind[keyof
 * Tailwind]`.
 * @see {@link https://github.com/danpacho/tailwindest#create-tailwind-type create-tailwind-type}
 *
 * @example
 * ```ts
 * // Compatibility fallback
 * import type { Tailwind } from "~/tailwind.ts"
 *
 * export type TailwindLiteral = CreateTailwindLiteral<Tailwind>
 * ```
 */
export type CreateTailwindLiteral<Tailwind> = Tailwind[keyof Tailwind]
